const searchIndex = {
  en: [
    {
      id: 'journal-rasp',
      category: 'journals',
      title: 'RASP - Revue Africaine de Sciences Sociales et de la Sante Publique',
      description: 'Pan-African bilingual open access journal covering sociology, anthropology, public health, psychology, and psychoanalysis.',
      path: '/journals',
      keywords: ['rasp', 'public health', 'sociology', 'anthropology', 'psychology', 'open access', 'journal'],
    },
    {
      id: 'journal-ajdi',
      category: 'journals',
      title: 'AJDI - African Journal for Development Informatics',
      description: 'Multidisciplinary open access journal focused on ICT, information systems, sustainability, and development.',
      path: '/journals',
      keywords: ['ajdi', 'informatics', 'ict', 'information systems', 'development', 'technology', 'journal'],
    },
    {
      id: 'policy-overview',
      category: 'policies',
      title: 'Publishing Policies Overview',
      description: 'Overview of BIRDs Press publishing policies and links to all detailed policy pages.',
      path: '/policies/overview',
      keywords: ['policies', 'overview', 'publishing policy'],
    },
    {
      id: 'policy-ethical',
      category: 'policies',
      title: 'Ethical Policies',
      description: 'Publication ethics, misconduct, corrections, retractions, complaints, and COPE-aligned standards.',
      path: '/policies/ethical',
      keywords: ['ethics', 'cope', 'misconduct', 'plagiarism', 'retractions', 'appeals'],
    },
    {
      id: 'policy-editorial',
      category: 'policies',
      title: 'Editorial Policy',
      description: 'Editorial independence, editorial screening, conflicts of interest, and special issue handling.',
      path: '/policies/editorial',
      keywords: ['editorial', 'editors', 'screening', 'special issues', 'conflicts of interest'],
    },
    {
      id: 'policy-peer-review',
      category: 'policies',
      title: 'Peer Review Policy',
      description: 'Double-blind peer review, reviewer selection, editorial decisions, timelines, and appeals.',
      path: '/policies/peer-review',
      keywords: ['peer review', 'double blind', 'reviewers', 'review timeline', 'appeals'],
    },
    {
      id: 'policy-post-decision',
      category: 'policies',
      title: 'Post-Decision Procedure',
      description: 'What happens after acceptance, revision requests, rejection, appeals, and production.',
      path: '/policies/post-decision',
      keywords: ['post decision', 'acceptance', 'minor revisions', 'major revisions', 'rejection', 'production'],
    },
    {
      id: 'policy-apc',
      category: 'policies',
      title: 'Article Processing Fee',
      description: 'Article processing charges, editorial independence, payment timing, and APC contact details.',
      path: '/policies/apc',
      keywords: ['apc', 'fees', 'article processing charges', 'payment', 'publication charges'],
    },
    {
      id: 'policy-open-access',
      category: 'policies',
      title: 'Open Access Policy',
      description: 'Immediate open access, reuse, licensing, discoverability, and preservation commitments.',
      path: '/policies/open-access',
      keywords: ['open access', 'licensing', 'reuse', 'discoverability', 'preservation'],
    },
    {
      id: 'policy-copyright',
      category: 'policies',
      title: 'Copyright and Licensing',
      description: 'Author copyright retention, CC BY 4.0 licensing, and rights for published articles.',
      path: '/policies/copyright',
      keywords: ['copyright', 'licensing', 'cc by', 'creative commons', 'author rights'],
    },
    {
      id: 'policy-reviewer-guidelines',
      category: 'policies',
      title: 'Reviewer Guidelines',
      description: 'Guidance for reviewers on confidentiality, objectivity, timeliness, and report preparation.',
      path: '/policies/reviewer-guidelines',
      keywords: ['reviewer', 'guidelines', 'confidentiality', 'objectivity', 'timeliness'],
    },
    {
      id: 'policy-advertising',
      category: 'policies',
      title: 'Advertising and Marketing Policy',
      description: 'Advertising practices, editorial independence, and promotion standards for journals.',
      path: '/policies/advertising',
      keywords: ['advertising', 'marketing', 'promotion', 'editorial independence'],
    },
    {
      id: 'policy-privacy',
      category: 'policies',
      title: 'Privacy Policy',
      description: 'Collection, use, sharing, retention, and protection of personal data.',
      path: '/policies/privacy',
      keywords: ['privacy', 'data protection', 'cookies', 'personal data', 'retention'],
    },
    {
      id: 'policy-archiving',
      category: 'policies',
      title: 'Archiving and Preservation Policy',
      description: 'Digital preservation, PKP Preservation Network, and self-archiving guidance.',
      path: '/policies/archiving',
      keywords: ['archiving', 'preservation', 'pkp', 'self-archiving', 'digital preservation'],
    },
    {
      id: 'policy-ai',
      category: 'policies',
      title: 'Artificial Intelligence (AI) Policy',
      description: 'How AI tools may be used in manuscripts, disclosure rules, and confidentiality expectations.',
      path: '/policies/ai-policy',
      keywords: ['ai', 'artificial intelligence', 'chatgpt', 'disclosure', 'authorship', 'generative ai'],
    },
  ],
  fr: [
    {
      id: 'journal-rasp',
      category: 'journals',
      title: 'RASP - Revue Africaine de Sciences Sociales et de la Sante Publique',
      description: 'Revue panafricaine bilingue en libre acces couvrant la sociologie, l anthropologie, la sante publique, la psychologie et la psychanalyse.',
      path: '/revues',
      keywords: ['rasp', 'sante publique', 'sociologie', 'anthropologie', 'psychologie', 'revue', 'acces libre'],
    },
    {
      id: 'journal-ajdi',
      category: 'journals',
      title: 'AJDI - African Journal for Development Informatics',
      description: 'Revue multidisciplinaire en libre acces consacree aux TIC, aux systemes d information, a la durabilite et au developpement.',
      path: '/revues',
      keywords: ['ajdi', 'informatique', 'tic', 'systemes d information', 'developpement', 'technologie', 'revue'],
    },
    {
      id: 'policy-overview',
      category: 'policies',
      title: 'Apercu des Politiques de Publication',
      description: 'Apercu des politiques de publication de BIRDs Press avec liens vers toutes les pages detaillees.',
      path: '/politiques/apercu',
      keywords: ['politiques', 'apercu', 'publication'],
    },
    {
      id: 'policy-ethical',
      category: 'policies',
      title: 'Politiques Ethiques',
      description: 'Ethique de publication, mauvaise conduite, corrections, retractions, plaintes et standards alignes sur le COPE.',
      path: '/politiques/ethique',
      keywords: ['ethique', 'cope', 'plagiat', 'retractions', 'plaintes', 'integrite'],
    },
    {
      id: 'policy-editorial',
      category: 'policies',
      title: 'Politique Editoriale',
      description: 'Independance editoriale, examen initial, conflits d interets et gestion des numeros speciaux.',
      path: '/politiques/editoriale',
      keywords: ['editoriale', 'editeurs', 'filtrage', 'conflits d interets', 'numeros speciaux'],
    },
    {
      id: 'policy-peer-review',
      category: 'policies',
      title: 'Politique d Evaluation par les Pairs',
      description: 'Evaluation en double aveugle, selection des evaluateurs, decisions editoriales, delais et recours.',
      path: '/politiques/evaluation-pairs',
      keywords: ['evaluation', 'pairs', 'double aveugle', 'evaluateurs', 'delais', 'recours'],
    },
    {
      id: 'policy-post-decision',
      category: 'policies',
      title: 'Procedure Post-Decision',
      description: 'Etapes apres acceptation, demandes de revision, rejet, recours et production.',
      path: '/politiques/post-decision',
      keywords: ['post decision', 'acceptation', 'revisions', 'rejet', 'production'],
    },
    {
      id: 'policy-apc',
      category: 'policies',
      title: 'Frais de Traitement des Articles',
      description: 'APC, frais de publication, independance editoriale, paiement et informations de contact.',
      path: '/politiques/frais-publication',
      keywords: ['apc', 'frais', 'paiement', 'publication', 'charges'],
    },
    {
      id: 'policy-open-access',
      category: 'policies',
      title: 'Politique d Acces Libre',
      description: 'Acces libre immediat, reutilisation, licence, decouvrabilite et preservation.',
      path: '/politiques/acces-libre',
      keywords: ['acces libre', 'licence', 'reutilisation', 'preservation', 'visibilite'],
    },
    {
      id: 'policy-copyright',
      category: 'policies',
      title: 'Droit d Auteur et Licence',
      description: 'Retention du droit d auteur, licence CC BY 4.0 et droits sur les articles publies.',
      path: '/politiques/droit-auteur',
      keywords: ['droit d auteur', 'licence', 'cc by', 'creative commons', 'droits'],
    },
    {
      id: 'policy-reviewer-guidelines',
      category: 'policies',
      title: 'Lignes Directrices pour les Evaluateurs',
      description: 'Confidentialite, objectivite, delais et preparation des rapports d evaluation.',
      path: '/politiques/directives-evaluateurs',
      keywords: ['evaluateurs', 'directives', 'confidentialite', 'objectivite', 'delais'],
    },
    {
      id: 'policy-advertising',
      category: 'policies',
      title: 'Politique de Publicite et de Marketing',
      description: 'Pratiques de publicite, independance editoriale et standards de promotion.',
      path: '/politiques/publicite',
      keywords: ['publicite', 'marketing', 'promotion', 'independance editoriale'],
    },
    {
      id: 'policy-privacy',
      category: 'policies',
      title: 'Politique de Confidentialite',
      description: 'Collecte, utilisation, partage, conservation et protection des donnees personnelles.',
      path: '/politiques/confidentialite',
      keywords: ['confidentialite', 'donnees personnelles', 'cookies', 'protection des donnees'],
    },
    {
      id: 'policy-archiving',
      category: 'policies',
      title: 'Politique d Archivage',
      description: 'Preservation numerique, PKP Preservation Network et auto-archivage.',
      path: '/politiques/archivage',
      keywords: ['archivage', 'preservation', 'pkp', 'auto archivage'],
    },
    {
      id: 'policy-ai',
      category: 'policies',
      title: 'Politique sur l IA',
      description: 'Usage des outils d IA, regles de declaration et exigences de confidentialite.',
      path: '/politiques/politique-ia',
      keywords: ['ia', 'intelligence artificielle', 'chatgpt', 'declaration', 'paternite scientifique'],
    },
  ],
};

export const getSearchIndex = (language) => searchIndex[language] || searchIndex.en;
